Repository wecode-bootcamp-korea/45-2nd-BESTful-frontend, pull requests merged in 2023-05, with the labels that each got.

#8 [45기 박현아] Add: dashboard 컴포넌트 추가
  package-lock.json
  package.json
  public/images/Components/dashboard/ex.png
  public/images/Components/profileImage/brunch.jpg
  public/images/Components/profileImage/ex.png
  src/components/Dashboard/Dashboard.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/pages/Main/Main.jsx
Labels: 멘토 리뷰 요청

#5 [45기 박현아] Add: custom hook 구현 (useInput, useFetch)
  src/hooks/useFetch.jsx
  src/hooks/useInput.jsx
Labels: 멘토 리뷰 요청

#6 [45기 연정아] Add: 포스트 업로드 레이아웃 추가
  src/pages/PostUpload/PostUpload.jsx
  src/pages/PostUpload/components/ContentsBox.jsx
Labels: 멘토 리뷰 요청

#9 [45기 박현아] Add: Body 공통 css 변경
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#10 [45기 연정아] 포스트 업로드 사진 추가 기능과 이미지 태깅 기능
  src/pages/PostUpload/PostUpload.jsx
  src/pages/PostUpload/components/ContentsBox.jsx
Labels: 멘토 리뷰 요청

#12 [45기 박현아] Add: dashboard 태그기능 구현
  src/components/Dashboard/Dashboard.jsx
  src/components/followingButton/FollowingButton.jsx
  src/components/tagButton/TagButton.jsx
Labels: 멘토 리뷰 요청

#15 [45기 박현아] Add: carousel, 더보기 구현
  package-lock.json
  package.json
  public/data/tagData.json
  public/favicon.ico
  public/favicon1.ico
  public/images/Components/dashboard/hanger.jpg
  public/images/Components/dashboard/icecream.jpg
  public/images/Components/dashboard/mickey_profile.jpg
  public/images/Components/dashboard/today.jpg
  public/images/logo/1.png
  public/images/logo/2.png
  public/images/logo/3.png
  public/images/logo/4.png
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/subComponent/ArrowButton.jsx
  src/components/Dashboard/subComponent/ArticleContent.jsx
  src/components/Dashboard/subComponent/Carousel.jsx
  src/components/Dashboard/subComponent/CarouselImage.jsx
Labels: 수정 요청

#16 [45기 박현아] Add: carousel내에서 tag의 모달 구현
  public/data/dashboardData.json
  public/data/tagData.json
  src/components/Dashboard/subComponent/ArticleContent.jsx
  src/components/Dashboard/subComponent/Carousel.jsx
  src/components/Dashboard/subComponent/CarouselImage.jsx
  src/components/Dashboard/subComponent/TagModal.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/components/tagButton/TagButton.jsx
Labels: 멘토 리뷰 요청

#14 [45기 이경진]Feature/my page
  package-lock.json
  package.json
  public/data/feedImage.json
  public/data/likeFeed.json
  public/data/user.json
  public/images/pages/Mypage/1.jpeg
  public/images/pages/Mypage/10.jpeg
  public/images/pages/Mypage/11.jpeg
  public/images/pages/Mypage/2.jpeg
  public/images/pages/Mypage/3.jpeg
  public/images/pages/Mypage/4.webp
  public/images/pages/Mypage/5.jpeg
  public/images/pages/Mypage/6.jpeg
  public/images/pages/Mypage/7.jpeg
  public/images/pages/Mypage/8.jpeg
  public/images/pages/Mypage/9.jpeg
  public/images/pages/Mypage/ex.png
  src/pages/Mypage/Component/ContentPosting/ContentPosting.jsx
  src/pages/Mypage/Component/ContentProfile/ContentProfile.jsx
  src/pages/Mypage/Component/FeedImage/FeedImage.jsx
  src/pages/Mypage/Component/ModifyInputs/ModifyInputs.jsx
  src/pages/Mypage/Component/MyPageCategory/MyPageCategory.jsx
  src/pages/Mypage/Component/MyPageContent/MyPageContent.jsx
  src/pages/Mypage/Component/ProfileModify/ProfileModify.jsx
  src/pages/Mypage/Mypage.jsx
Labels: 멘토 리뷰 요청

#20 [45기 문유현] feature/main-layout [리뷰 반영 / 리액트 아이콘스 삭제]
  src/pages/Main/Main.jsx
  src/pages/Main/components/FilterCategory.jsx
  src/pages/Main/components/FilterDetail.jsx
  src/pages/Main/components/MainFooter.jsx
  src/pages/Main/components/OptionInput.jsx
Labels: 멘토 리뷰 요청

#19 [45기 박현아] Add: 팔로우 보이는 컴포넌트 추가
  public/data/followDisplayData.json
  src/components/Container/Container.jsx
  src/components/FollowDisplay/FollowDisplay.jsx
  src/components/FollowDisplay/subComponent/FollowElement.jsx
  src/components/followingButton/FollowingButton.jsx
  src/pages/Users/Users.jsx
Labels: 멘토 리뷰 요청

#17 [45기 오승민] Add: 카카오로그인 레이아웃, 기능 구현
  package-lock.json
  package.json
  public/index.html
  src/Router.jsx
  src/components/Nav/Nav.jsx
  src/index.js
  src/pages/Login/Login.jsx
  src/pages/Login/components/ContentContainer.jsx
Labels: 멘토 리뷰 요청

#23 [45기 박현아] Add: 피드 상세페이지 레이아웃 구현
  src/components/Dashboard/subComponent/Carousel.jsx
  src/components/FollowDisplay/FollowDisplay.jsx
  src/components/FollowDisplay/subComponent/FollowElement.jsx
  src/components/followingButton/FollowingButton.jsx
  src/pages/Contents/Contents.jsx
  src/pages/Contents/component/Comment.jsx
  src/pages/Contents/component/CommentElement.jsx
  src/pages/Contents/component/FeedImage.jsx
  src/pages/Contents/component/InputPart.jsx
  src/pages/Contents/component/ProfileBox.jsx
  src/pages/Contents/component/SideBar.jsx
  src/pages/Contents/component/SidePhoto.jsx
Labels: 리뷰 진행 중

#25 [45기 오승민] Add: Nav 레이아웃
  public/images/logo/hanger.png
  src/components/Nav/Nav.jsx
Labels: 멘토 리뷰 요청

#21 [45기 연정아] 태그에 정보 입력
  public/data/dashboardData.json
  public/data/feedImage.json
  public/data/likeFeed.json
  public/data/tagData.json
  public/data/user.json
  src/components/Dashboard/subComponent/ArticleContent.jsx
  src/components/Dashboard/subComponent/CarouselImage.jsx
  src/components/Dashboard/subComponent/TagModal.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/components/tagButton/TagButton.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/components/FilterCategory.jsx
  src/pages/Main/components/FilterDetail.jsx
  src/pages/Main/components/MainFooter.jsx
  src/pages/Main/components/OptionInput.jsx
  src/pages/Mypage/Component/ContentPosting/ContentPosting.jsx
  src/pages/Mypage/Component/ContentProfile/ContentProfile.jsx
  src/pages/Mypage/Component/FeedImage/FeedImage.jsx
  src/pages/Mypage/Component/ModifyInputs/ModifyInputs.jsx
  src/pages/Mypage/Component/MyPageCategory/MyPageCategory.jsx
  src/pages/Mypage/Component/MyPageContent/MyPageContent.jsx
  src/pages/Mypage/Component/ProfileModify/ProfileModify.jsx
  src/pages/Mypage/Mypage.jsx
  src/pages/PostUpload/PostUpload.jsx
  src/pages/PostUpload/components/ContentsBox.jsx
  src/pages/PostUpload/components/PostTagButton.jsx
  src/pages/PostUpload/components/PostTagModal.jsx
  src/pages/PostUpload/components/StyleInput.jsx
  src/pages/PostUpload/components/TagContainer.jsx
  src/pages/PostUpload/components/UploadImg.jsx
Labels: 멘토 리뷰 요청

#27 [45기 문유현 ] feature/main-infiniteScroll
  package-lock.json
  package.json
  public/data/feedList.json
  src/Router.jsx
  src/pages/Best/Best.jsx
  src/pages/Best/components/BestCarousel.jsx
  src/pages/Following/Following.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MainInfinite.jsx
  src/pages/Main/components/FilterCategory.jsx
  src/pages/Main/components/FilterDetail.jsx
  src/pages/Main/components/MainFooter.jsx
  src/pages/Main/components/OptionInput.jsx
Labels: 멘토 리뷰 요청

#24 [45기 박현아] Add: dashboard에 실제 data 적용
  public/data/dashboardData.json
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/subComponent/Carousel.jsx
  src/components/Dashboard/subComponent/CarouselImage.jsx
  src/components/Dashboard/subComponent/FollowButton.jsx
  src/components/Dashboard/subComponent/TagModal.jsx
  src/pages/Main/Main.jsx
Labels: 멘토 리뷰 요청

#29 [45기 오승민] Add : Footer 완성
  src/components/Footer/Footer.jsx
Labels: 멘토 리뷰 요청

#30 [45기 박현아] Add: 피드상세페이지 변수적용, 통신완료
  public/data/commentData.json
  public/data/dashboardData.json
  public/images/logo/noProfile.png
  public/images/pages/Contents/warning.jpg
  src/Router.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/subComponent/Carousel.jsx
  src/components/Dashboard/subComponent/CarouselImage.jsx
  src/components/Dashboard/subComponent/TagModal.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/pages/Contents/Contents.jsx
  src/pages/Contents/InvalidAccess.jsx
  src/pages/Contents/component/Comment.jsx
  src/pages/Contents/component/CommentElement.jsx
  src/pages/Contents/component/FeedImage.jsx
  src/pages/Contents/component/InputPart.jsx
  src/pages/Contents/component/ProfileBox.jsx
  src/pages/Contents/component/SideBar.jsx
  src/pages/Contents/component/SidePhoto.jsx
  src/pages/Main/Main.jsx
Labels: 멘토 리뷰 요청

#32 [45기 오승민] Add: Nav 기능 구현
  public/images/logo/title.png
  src/components/Footer/Footer.jsx
  src/components/Nav/Nav.jsx
  src/components/Nav/components/NavProfileImage.jsx
  src/components/ProfileImage/ProfileImage.jsx
  src/pages/Login/components/ContentContainer.jsx
Labels: 멘토 리뷰 요청

#26 [45기 연정아] 포스트 업로드 세부 기능 구현
  src/pages/PostUpload/PostUpload.jsx
  src/pages/PostUpload/components/ContentsBox.jsx
  src/pages/PostUpload/components/PostTagModal.jsx
  src/pages/PostUpload/components/StyleInput.jsx
  src/pages/PostUpload/components/TagContainer.jsx
  src/pages/PostUpload/components/UploadImg.jsx
Labels: 멘토 리뷰 요청

#33 [45기 박현아] Add: 통신후 수정
  src/Router.jsx
  src/components/Dashboard/Dashboard.jsx
  src/components/Dashboard/subComponent/Carousel.jsx
  src/components/Dashboard/subComponent/FollowButton.jsx
  src/components/Dashboard/subComponent/TagModal.jsx
  src/components/Footer/Footer.jsx
  src/pages/Best/Best.jsx
  src/pages/Contents/Contents.jsx
  src/pages/Contents/component/Comment.jsx
  src/pages/Contents/component/CommentElement.jsx
  src/pages/Contents/component/InputPart.jsx
  src/pages/Contents/component/SideBar.jsx
  src/pages/Contents/component/SidePhoto.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MainInfinite.jsx
  src/pages/Mypage/Component/ContentProfile/ContentProfile.jsx
  src/pages/Mypage/Component/ModifyInputs/ModifyInputs.jsx
  src/pages/Mypage/Component/MyPageContent/MyPageContent.jsx
  src/pages/Users/Component/UserContent/UserContent.jsx
Labels: 멘토 리뷰 요청

#35 [45기 이경진] 마이페이지 & 유저 페이지 최종완료
  src/components/FollowDisplay/FollowDisplay.jsx
  src/components/FollowDisplay/subComponent/FollowElement.jsx
  src/components/FollowerPage/FollowerContent/FollowerContent.jsx
  src/components/FollowerPage/FollowerList/FollowerList.jsx
  src/components/FollowerPage/FollowerPage.jsx
  src/components/FollowingPage/FollowingBtn/FollowingBtn.jsx
  src/components/FollowingPage/FollowingContent/FollowingContent.jsx
  src/components/FollowingPage/FollowingList/FollowingList.jsx
  src/components/FollowingPage/FollowingPage.jsx
  src/components/UserFollower/UserFollower.jsx
  src/components/UserFollower/UserFollowerBtn/UserFollowerBtn.jsx
  src/components/UserFollower/UserFollowerContent/UserFollowerContent.jsx
  src/components/UserFollower/UserFollowerList/UserFollowerList.jsx
  src/components/UserFollowing/UserFollowing.jsx
  src/components/UserFollowing/UserFollowingBtn/UserFollowingBtn.jsx
  src/components/UserFollowing/UserFollowingContent/UserFollowingContent.jsx
  src/components/UserFollowing/UserFollowingList/UserFollowingList.jsx
  src/pages/Mypage/Component/ContentPosting/ContentPosting.jsx
  src/pages/Mypage/Component/ContentProfile/ContentProfile.jsx
  src/pages/Mypage/Component/FeedImage/FeedImage.jsx
  src/pages/Mypage/Component/ModifyInputs/ModifyInputs.jsx
  src/pages/Mypage/Component/MyPageCategory/MyPageCategory.jsx
  src/pages/Mypage/Component/MyPageContent/MyPageContent.jsx
  src/pages/Mypage/Mypage.jsx
  src/pages/Users/Component/ContentImage/ContentImage.jsx
  src/pages/Users/Component/UserContent/UserContent.jsx
  src/pages/Users/Component/UserProfile/UserProfile.jsx
Labels: 멘토 리뷰 요청
